### ISSUE TITLE
How to make it work with OBS?

### ISSUE THREAD

**Issue by olegzvg** [JakubKoralewski/cursor-recorder#10]
![Annotation 2019-12-13 210037](https://user-images.githubusercontent.com/58860264/70821309-d964bf80-1deb-11ea-9b4c-83a68bbefdd6.jpg)
Is this how it should look like? I'm totally new with OBS, didn't know anything about python, so maybe i did something wrong. I've installed python and those two requirements, standalone version seems to work, but OBS isn't.

> Make sure the script is enabled. (It is by default).
Where i can enable it? 

I've searched cursor tracker already for weeks, i'm glad that you're doing it, thank you very much, keep it up. I want to fed it into houdini. I'm not able to use standalone because I'm hitting escape key prety often.

**Comment by JakubKoralewski** [comment]
Sorry for missing your issue 😭 

Hmm. Interesting. Couple things:

1. Firstly, make sure your installed and configured Python version is 3.6.
2. If you're sure you have the right version, could you provide a screenshot of the `Python Settings` tab to make sure you set the Python interpreter correctly? As shown here:
> Make sure you have a Python (3.6.x) interpreter installed and **its path set in OBS' settings (Scripts -> Python Settings).**
3. Alternatively, have you tried the newly released version 4? See here: https://github.com/JakubKoralewski/cursor-recorder/releases/tag/v0.4

There seemed to be some issues before where `pyautogui` and `keyboard` were not installed. If none of the above works try to run the following in your terminal: `pip install pyautogui keyboard`.

Cheers.

BTW. Thank you for the kind words.

> I want to fed it into houdini.

Wow, never grasped Vex and Houdini. What's your use case (if it's not a secret 😅) ?

**Comment by JakubKoralewski** [comment]
@olegzvg did you manage to get it working? what was the problem? 

you could also try to change the key needed to stop it here from esc to something else https://github.com/JakubKoralewski/cursor-recorder/blob/7957176a9150b59507aa11219f32ec5babf47848/scripts/cursor_recorder_standalone.py#L65
or we could think about a feature to exit with ctrl+c like regular scripts

**Comment by olegzvg** [comment]
nah, I even forgot why I want it sorry. perhaps to track cursor for small tutorials for social media, but now i think fast movement will distract from information so it's better to make it manually since in will be short enough to avoid automation. maybe i was just high and experimented with data. five years, now i gonna dive into jon hopkins singularity again, like back then, thanks.

**Comment by JakubKoralewski** [comment]
i'll check that song out

**Comment by olegzvg** [comment]
plaese check the full album, i'm talking about album. with your eyes closed and nice headphones, like audiotechnica
