### ISSUE TITLE
File "<fstring>", line 1  (name=) ^SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by nicolasdupouymanescau** [JakubKoralewski/cursor-recorder#18]
`[cursor_recorder_for_obs.py]   File "<fstring>", line 1`
`[cursor_recorder_for_obs.py]     (name=)`
`[cursor_recorder_for_obs.py]          ^`
`[cursor_recorder_for_obs.py] SyntaxError: invalid syntax`

log from the latest version (the one that is 22.626 Ko), also I see no UI and no description  😢 
![image](https://github.com/JakubKoralewski/cursor-recorder/assets/132411106/9d18592b-a69c-4d74-a538-de7c87e32639)

**Comment by nicolasdupouymanescau** [comment]
I am talking about the #17 , since the code hasn't been merged into master, I leave this issue close. If it makes sense.

**Comment by JakubKoralewski** [comment]
It's fine to leave it open, if it happens for you it's a valid issue.
What python version have you set in OBS settings? I believe fstrings are available since 3.6

**Comment by JakubKoralewski** [comment]
The feature I used actually requires 3.8+ :/ 
https://stackoverflow.com/a/59661963

I'll remove that line, I think it was just for debugging.
